steps:
# Region segmentation
  - step: Segmentation
    settings:
      model: yolo
      model_settings:
        model: Riksarkivet/yolov9-regions-1
      generation_settings:
        batch_size: 2
  # Line segementation
  - step: Segmentation
    settings:
      model: yolo
      model_settings:
        model: Riksarkivet/yolov9-lines-within-regions-1
      generation_settings:
          batch_size: 2

  # Export to Alto and Page XML
  - step: Export
    settings:
      dest: output/htrflow/polis_line_segmentation/alto
      format: alto
  - step: Export
    settings:
      dest: output/htrflow/polis_line_segmentation/page
      format: page

# Sets label format to regionX_lineY_wordZ
labels:
  level_labels:
    - region
    - line
    - word
  sep: _
  template: "{label}{number}"